language: android
sudo: required
jdk: oraclejdk8

android:
  components:
    - platform-tools
    - tools
    # The BuildTools version used by your project
    - build-tools-29.0.0
    # The SDK version used to compile your project
    - android-29
    - android-24
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-x86-android-23

before_install:
  - yes | sdkmanager "platforms;android-29"

before_script:
  # Create and start emulator
  - echo "y" | android update sdk -a --no-ui --filter android-24
  - echo "y" | android update sdk -a --no-ui --filter sys-img-armeabi-v7a-android-24
  - echo no | android create avd --force -n test -t android-24 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script: ./gradlew connectedAndroidTest

after_success:
  - bash echo "Yata!"